server:
  port: 8080

# Actuator
management:
  endpoint:
    loggers:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  swagger-ui:
    disable-swagger-default-url: true